### PR TITLE
Feet icon on collection shipping label

### PR DESCRIPTION
**Pull request by mbarton**
Screenshot 2021-11-17 18 58 59

### CODE REVIEW

**Comment by dan-langridge** [comment]
Love this

**Comment by dan-langridge** [comment]
What does it look like when it's Delivery?

**Comment by mbarton** [comment]
@dan-langridge I kept it the same as before, just time of day and the word delivery Screenshot 2021-11-19 13 02 06

**Comment by adamcunnington** [comment]
@dan-langridge happy for this to be merged?

**Comment by dan-langridge** [comment]
Happy to merge 👍 thanks

**Review by adamcunnington — APPROVED** [review]

**Pull request merged**
