### PR TITLE
Add truck and feet css class, collection site details and icon (failing)

### PR DESCRIPTION
**Pull request by adamcunnington**
I have added 2 things to the shopping list form:
- Collection centre details in text form (see below screenshot)
- Feet or truck icon after the title (but this doesn't work - currently produces empty gap in the pdf) - @mbarton please can you take a look?
image

Also, I don't see the foodbank logo here - @dan-langridge can you advise whether this is the case on the live site? I can't recall if this was working - I see from the code that we use a different method to how Michael figured out we had to embed pictures into the PDFs so it's possible that the picture has never worked but we didn't care?

### CODE REVIEW

**Comment by dan-langridge** [comment]
@adamcunnington I can confirm the FoodBank Logo does appear on the live site and is working fine

**Comment by mbarton** [comment]
@adamcunnington have pushed a fix to the icon. It wasn't showing up because it needed a height attribute in CSS as well as width. For this hack the browser will assume zero width/height by default as technically it has no content, just a background image. 1em for the height/width means it will now scale along with the line-height of the parent h1. Tbh I don't know why I didn't just put the data URL as the src for an img tag originally, that would have avoided this problem.

I've also added a sprinkling of flexbox to vertically align the icon and replaced the data URLs with slightly higher-res screengrabs so the icons look less fuzzy now they're bigger.

Screenshot 2021-11-19 16 21 09


Screenshot 2021-11-19 16 21 04

**Comment by adamcunnington** [comment]
@mbarton amazing, thank you!

**Comment by adamcunnington** [comment]
@dan-langridge happy for this to be merged based on screenshots? note the icon as well as collection details before the table starts

**Comment by dan-langridge** [comment]
All looks great, thanks guys. Happy to merge

**Comment by dan-langridge** [comment]
is foodbank logo still missing top right from your PDF @mbarton ? Or is this something that will magically work in Prod like @adamcunnington  says?

**Comment by adamcunnington** [comment]
I guess it's because we use a different method in the HTML to grab the foodbank logo - although I don't quite understand why this works on prod and note locally via docker container...

**Comment by mbarton** [comment]
@adamcunnington in all cases Weasyprint just downloading an image over HTTP. We use Flask's `url_for` function to generate the URL though, which is context dependent. For the local dev build it returns `http://localhost:5000/logo.png`. The frontend dev build (which has the logo) runs on 3000 so it 404s unless you do an `npm run build` to put the files in the right place. This is what makes prod work too (I think).

Running in docker it's port forwarding. With the default `-p 80:8080`, `url_for` thinks it's running on port 80 but it's actually running on 8080 in the container so fails with `Failed to load image at 'http://localhost/logo.png': URLError: <urlopen error [Errno 99] Cannot assign requested address>`. If I change it to `-p 8080:8080` it works.

**Pull request merged**
